FROM eclipse-temurin:17 as builder
RUN mkdir /app
WORKDIR /app
COPY iam-test-client.jar /app/
RUN java -Djarmode=layertools -jar iam-test-client.jar extract

FROM eclipse-temurin:17
RUN mkdir /app
WORKDIR /app

COPY --from=builder app/dependencies/ ./
COPY --from=builder app/spring-boot-loader/ ./
COPY --from=builder app/snapshot-dependencies/ ./
COPY --from=builder app/application/ ./

CMD java ${IAM_CLIENT_JAVA_OPTS} org.springframework.boot.loader.JarLauncher
