spring:
  mvc:
    view:
      suffix: .html

server:
  servlet:
    context-path: /iam-test-client 
  
  port: ${IAM_CLIENT_PORT:9090}

  forward-headers-strategy: ${IAM_CLIENT_FORWARD_HEADERS_STRATEGY:none}

iam:
    issuer: ${IAM_CLIENT_ISSUER:http://localhost:8443/}
    organizationName: ${IAM_CLIENT_ORGANIZATION_NAME:indigo-dc}
    extAuthnHint: ${IAM_CLIENT_EXT_AUTHN_HINT:}
    
    hide-tokens: ${IAM_CLIENT_HIDE_TOKENS:true}
    
    tls:
      version: ${IAM_CLIENT_TLS_VERSION:TLSv1.2}
      ignore-namespace-checks: ${IAM_CLIENT_TLS_IGNORE_NAMESPACE_CHECKS:false} 
      use-grid-trust-anchors: ${IAM_CLIENT_TLS_USE_GRID_TRUST_ANCHORS:false}
      
    client:
      clientId: ${IAM_CLIENT_ID:client}
      clientSecret: ${IAM_CLIENT_SECRET:secret}
      redirectUris: ${IAM_CLIENT_REDIRECT_URIS:http://localhost:9090/iam-test-client/openid_connect_login}
      scope: ${IAM_CLIENT_SCOPES:openid profile email}
      