DELETE FROM AUTHENTICATION_HOLDER WHERE ID=1;
DELETE FROM SAVED_USER_AUTH WHERE ID=1;
DELETE FROM SAVED_USER_AUTH_AUTHORITY WHERE OWNER_ID=1;
DELETE FROM AUTHENTICATION_HOLDER_SCOPE WHERE OWNER_ID=1;
DELETE FROM AUTHENTICATION_HOLDER_EXTENSION WHERE OWNER_ID=1;
DELETE FROM AUTHENTICATION_HOLDER_REQUEST_PARAMETER WHERE OWNER_ID=1;