CREATE TABLE authentication_holder (id BIGINT IDENTITY NOT NULL, approved BOOLEAN, client_id VARCHAR, redirect_uri VARCHAR, user_auth_id BIGINT, PRIMARY KEY (id))
CREATE TABLE authorization_code (id BIGINT IDENTITY NOT NULL, code VARCHAR, expiration TIMESTAMP, auth_holder_id BIGINT, PRIMARY KEY (id))
CREATE TABLE client_details (id BIGINT IDENTITY NOT NULL, access_token_validity_seconds INTEGER, allow_introspection BOOLEAN, application_type VARCHAR, clear_access_tokens_on_refresh BOOLEAN, client_description VARCHAR, client_id VARCHAR, client_name VARCHAR, client_secret VARCHAR, client_uri VARCHAR, created_at TIMESTAMP, default_max_age INTEGER, dynamically_registered BOOLEAN, id_token_encrypted_response_alg VARCHAR, id_token_encrypted_response_enc VARCHAR, id_token_signed_response_alg VARCHAR, id_token_validity_seconds INTEGER, initiate_login_uri VARCHAR, jwks VARCHAR, jwks_uri VARCHAR, logo_uri VARCHAR, policy_uri VARCHAR, refresh_token_validity_seconds INTEGER, request_object_signing_alg VARCHAR, require_auth_time BOOLEAN, reuse_refresh_tokens BOOLEAN, sector_identifier_uri VARCHAR, subject_type VARCHAR, token_endpoint_auth_method VARCHAR, token_endpoint_auth_signing_alg VARCHAR, tos_uri VARCHAR, user_info_encrypted_response_alg VARCHAR, user_info_encrypted_response_enc VARCHAR, user_info_signed_response_alg VARCHAR, PRIMARY KEY (id))
CREATE TABLE access_token (id BIGINT IDENTITY NOT NULL, expiration TIMESTAMP, token_value VARCHAR, token_type VARCHAR, auth_holder_id BIGINT, client_id BIGINT, refresh_token_id BIGINT, id_token_id BIGINT, approved_site_id BIGINT, PRIMARY KEY (id))
CREATE TABLE refresh_token (id BIGINT IDENTITY NOT NULL, expiration TIMESTAMP, token_value VARCHAR, auth_holder_id BIGINT, client_id BIGINT, PRIMARY KEY (id))
CREATE TABLE saved_user_auth (id BIGINT IDENTITY NOT NULL, authenticated BOOLEAN, name VARCHAR, source_class VARCHAR, PRIMARY KEY (id))
CREATE TABLE system_scope (id BIGINT IDENTITY NOT NULL, default_scope BOOLEAN, description VARCHAR, icon VARCHAR, restricted BOOLEAN, structured BOOLEAN, structured_param_description VARCHAR, scope VARCHAR, PRIMARY KEY (id))
CREATE TABLE approved_site (id BIGINT IDENTITY NOT NULL, access_date TIMESTAMP, client_id VARCHAR, creation_date TIMESTAMP, timeout_date TIMESTAMP, user_id VARCHAR, PRIMARY KEY (id))
CREATE TABLE blacklisted_site (id BIGINT IDENTITY NOT NULL, uri VARCHAR, PRIMARY KEY (id))
CREATE TABLE address (id BIGINT IDENTITY NOT NULL, country VARCHAR, formatted VARCHAR, locality VARCHAR, postal_code VARCHAR, region VARCHAR, street_address VARCHAR, PRIMARY KEY (id))
CREATE TABLE user_info (id BIGINT IDENTITY NOT NULL, birthdate VARCHAR, email VARCHAR, email_verified BOOLEAN, family_name VARCHAR, gender VARCHAR, given_name VARCHAR, locale VARCHAR, middle_name VARCHAR, name VARCHAR, nickname VARCHAR, phone_number VARCHAR, phone_number_verified BOOLEAN, picture VARCHAR, preferred_username VARCHAR, profile VARCHAR, src VARCHAR, sub VARCHAR, updated_time VARCHAR, website VARCHAR, zone_info VARCHAR, address_id BIGINT, PRIMARY KEY (id))
CREATE TABLE pairwise_identifier (id BIGINT IDENTITY NOT NULL, identifier VARCHAR, sector_identifier VARCHAR, sub VARCHAR, PRIMARY KEY (id))
CREATE TABLE whitelisted_site (id BIGINT IDENTITY NOT NULL, client_id VARCHAR, creator_user_id VARCHAR, PRIMARY KEY (id))
CREATE TABLE claim (id BIGINT IDENTITY NOT NULL, claim_type VARCHAR, friendly_name VARCHAR, name VARCHAR, claim_value VARCHAR, PRIMARY KEY (id))
CREATE TABLE permission (id BIGINT IDENTITY NOT NULL, resource_set_id BIGINT, PRIMARY KEY (id))
CREATE TABLE permission_ticket (id BIGINT IDENTITY NOT NULL, expiration TIMESTAMP, ticket VARCHAR, permission_id BIGINT, PRIMARY KEY (id))
CREATE TABLE policy (id BIGINT IDENTITY NOT NULL, name VARCHAR, resource_set_id BIGINT, PRIMARY KEY (id))
CREATE TABLE resource_set (id BIGINT IDENTITY NOT NULL, client_id VARCHAR, icon_uri VARCHAR, name VARCHAR, owner VARCHAR, rs_type VARCHAR, uri VARCHAR, PRIMARY KEY (id))
CREATE TABLE saved_registered_client (id BIGINT IDENTITY NOT NULL, issuer VARCHAR, registered_client VARCHAR, PRIMARY KEY (id))
CREATE TABLE iam_account (ID BIGINT IDENTITY NOT NULL, active BOOLEAN NOT NULL, CREATIONTIME TIMESTAMP NOT NULL, LASTUPDATETIME TIMESTAMP NOT NULL, PASSWORD VARCHAR(128), USERNAME VARCHAR(128) NOT NULL UNIQUE, UUID VARCHAR(36) NOT NULL UNIQUE, user_info_id BIGINT, PRIMARY KEY (ID))
CREATE TABLE iam_authority (ID BIGINT IDENTITY NOT NULL, auth VARCHAR(128) NOT NULL UNIQUE, PRIMARY KEY (ID))
CREATE TABLE iam_group (ID BIGINT IDENTITY NOT NULL, CREATIONTIME TIMESTAMP NOT NULL, DESCRIPTION VARCHAR(512), LASTUPDATETIME TIMESTAMP NOT NULL, NAME VARCHAR(255) NOT NULL UNIQUE, UUID VARCHAR(36) NOT NULL UNIQUE, PRIMARY KEY (ID))
CREATE TABLE iam_oidc_id (ID BIGINT IDENTITY NOT NULL, ISSUER VARCHAR(256) NOT NULL, SUBJECT VARCHAR(256) NOT NULL, account_id BIGINT, PRIMARY KEY (ID))
CREATE TABLE iam_saml_id (ID BIGINT IDENTITY NOT NULL, IDPID VARCHAR(256) NOT NULL, USERID VARCHAR(256) NOT NULL, account_id BIGINT, PRIMARY KEY (ID))
CREATE TABLE iam_ssh_key (ID BIGINT IDENTITY NOT NULL, LABEL VARCHAR(36) NOT NULL UNIQUE, is_primary BOOLEAN, VALUE LONGVARCHAR UNIQUE, ACCOUNT_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE iam_user_info (ID BIGINT IDENTITY NOT NULL, BIRTHDATE VARCHAR, EMAIL VARCHAR(128) NOT NULL, EMAILVERIFIED BOOLEAN, FAMILYNAME VARCHAR(64) NOT NULL, GENDER VARCHAR, GIVENNAME VARCHAR(64) NOT NULL, LOCALE VARCHAR, MIDDLENAME VARCHAR(64), NICKNAME VARCHAR, PHONENUMBER VARCHAR, PHONENUMBERVERIFIED BOOLEAN, PICTURE VARCHAR, PROFILE VARCHAR, WEBSITE VARCHAR, ZONEINFO VARCHAR, ADDRESS_ID BIGINT, DTYPE VARCHAR(31), PRIMARY KEY (ID))
CREATE TABLE iam_x509_cert (ID BIGINT IDENTITY NOT NULL, CERTIFICATESUBJECT VARCHAR(128) NOT NULL UNIQUE, LABEL VARCHAR(36) NOT NULL UNIQUE, is_primary BOOLEAN, ACCOUNT_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE authentication_holder_authority (owner_id BIGINT, authority VARCHAR)
CREATE TABLE authentication_holder_resource_id (owner_id BIGINT, resource_id VARCHAR)
CREATE TABLE authentication_holder_response_type (owner_id BIGINT, response_type VARCHAR)
CREATE TABLE authentication_holder_scope (owner_id BIGINT, scope VARCHAR)
CREATE TABLE authentication_holder_extension (owner_id BIGINT, val VARCHAR, extension VARCHAR)
CREATE TABLE authentication_holder_request_parameter (owner_id BIGINT, val VARCHAR, param VARCHAR)
CREATE TABLE client_authority (owner_id BIGINT, authority VARCHAR)
CREATE TABLE client_claims_redirect_uri (owner_id BIGINT, redirect_uri VARCHAR)
CREATE TABLE client_contact (owner_id BIGINT, contact VARCHAR)
CREATE TABLE client_default_acr_value (owner_id BIGINT, default_acr_value VARCHAR)
CREATE TABLE client_grant_type (owner_id BIGINT, grant_type VARCHAR)
CREATE TABLE client_post_logout_redirect_uri (owner_id BIGINT, post_logout_redirect_uri VARCHAR)
CREATE TABLE client_redirect_uri (owner_id BIGINT, redirect_uri VARCHAR)
CREATE TABLE client_request_uri (owner_id BIGINT, request_uri VARCHAR)
CREATE TABLE client_resource (owner_id BIGINT, resource_id VARCHAR)
CREATE TABLE client_response_type (owner_id BIGINT, response_type VARCHAR)
CREATE TABLE client_scope (owner_id BIGINT, scope VARCHAR)
CREATE TABLE token_scope (owner_id BIGINT, SCOPE VARCHAR)
CREATE TABLE access_token_permissions (access_token_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, PRIMARY KEY (access_token_id, permission_id))
CREATE TABLE saved_user_auth_authority (owner_id BIGINT, authority VARCHAR)
CREATE TABLE approved_site_scope (owner_id BIGINT, scope VARCHAR)
CREATE TABLE whitelisted_site_scope (owner_id BIGINT, scope VARCHAR)
CREATE TABLE claim_token_format (owner_id BIGINT, claim_token_format VARCHAR)
CREATE TABLE claim_issuer (owner_id BIGINT, issuer VARCHAR)
CREATE TABLE permission_scope (owner_id BIGINT, scope VARCHAR)
CREATE TABLE claim_to_permission_ticket (permission_ticket_id BIGINT NOT NULL, claim_id BIGINT NOT NULL, PRIMARY KEY (permission_ticket_id, claim_id))
CREATE TABLE policy_scope (owner_id BIGINT, scope VARCHAR)
CREATE TABLE claim_to_policy (policy_id BIGINT NOT NULL, claim_id BIGINT NOT NULL, PRIMARY KEY (policy_id, claim_id))
CREATE TABLE resource_set_scope (owner_id BIGINT, scope VARCHAR)
CREATE TABLE iam_account_authority (account_id BIGINT NOT NULL, authority_id BIGINT NOT NULL, PRIMARY KEY (account_id, authority_id))
CREATE TABLE iam_account_group (account_id BIGINT NOT NULL, group_id BIGINT NOT NULL, PRIMARY KEY (account_id, group_id))
ALTER TABLE authentication_holder ADD CONSTRAINT FK_authentication_holder_user_auth_id FOREIGN KEY (user_auth_id) REFERENCES saved_user_auth (id)
ALTER TABLE authorization_code ADD CONSTRAINT FK_authorization_code_auth_holder_id FOREIGN KEY (auth_holder_id) REFERENCES authentication_holder (id)
ALTER TABLE access_token ADD CONSTRAINT FK_access_token_refresh_token_id FOREIGN KEY (refresh_token_id) REFERENCES refresh_token (id)
ALTER TABLE access_token ADD CONSTRAINT FK_access_token_id_token_id FOREIGN KEY (id_token_id) REFERENCES access_token (id)
ALTER TABLE access_token ADD CONSTRAINT FK_access_token_auth_holder_id FOREIGN KEY (auth_holder_id) REFERENCES authentication_holder (id)
ALTER TABLE access_token ADD CONSTRAINT FK_access_token_client_id FOREIGN KEY (client_id) REFERENCES client_details (id)
ALTER TABLE access_token ADD CONSTRAINT FK_access_token_approved_site_id FOREIGN KEY (approved_site_id) REFERENCES approved_site (id)
ALTER TABLE refresh_token ADD CONSTRAINT FK_refresh_token_client_id FOREIGN KEY (client_id) REFERENCES client_details (id)
ALTER TABLE refresh_token ADD CONSTRAINT FK_refresh_token_auth_holder_id FOREIGN KEY (auth_holder_id) REFERENCES authentication_holder (id)
ALTER TABLE user_info ADD CONSTRAINT FK_user_info_address_id FOREIGN KEY (address_id) REFERENCES address (id)
ALTER TABLE permission ADD CONSTRAINT FK_permission_resource_set_id FOREIGN KEY (resource_set_id) REFERENCES resource_set (id)
ALTER TABLE permission_ticket ADD CONSTRAINT FK_permission_ticket_permission_id FOREIGN KEY (permission_id) REFERENCES permission (id)
ALTER TABLE policy ADD CONSTRAINT FK_policy_resource_set_id FOREIGN KEY (resource_set_id) REFERENCES resource_set (id)
ALTER TABLE iam_account ADD CONSTRAINT FK_iam_account_user_info_id FOREIGN KEY (user_info_id) REFERENCES iam_user_info (ID)
ALTER TABLE iam_oidc_id ADD CONSTRAINT FK_iam_oidc_id_account_id FOREIGN KEY (account_id) REFERENCES iam_account (ID)
ALTER TABLE iam_saml_id ADD CONSTRAINT FK_iam_saml_id_account_id FOREIGN KEY (account_id) REFERENCES iam_account (ID)
ALTER TABLE iam_ssh_key ADD CONSTRAINT FK_iam_ssh_key_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES iam_account (ID)
ALTER TABLE iam_x509_cert ADD CONSTRAINT FK_iam_x509_cert_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES iam_account (ID)
ALTER TABLE authentication_holder_authority ADD CONSTRAINT FK_authentication_holder_authority_owner_id FOREIGN KEY (owner_id) REFERENCES authentication_holder (id)
ALTER TABLE authentication_holder_resource_id ADD CONSTRAINT FK_authentication_holder_resource_id_owner_id FOREIGN KEY (owner_id) REFERENCES authentication_holder (id)
ALTER TABLE authentication_holder_response_type ADD CONSTRAINT FK_authentication_holder_response_type_owner_id FOREIGN KEY (owner_id) REFERENCES authentication_holder (id)
ALTER TABLE authentication_holder_scope ADD CONSTRAINT FK_authentication_holder_scope_owner_id FOREIGN KEY (owner_id) REFERENCES authentication_holder (id)
ALTER TABLE authentication_holder_extension ADD CONSTRAINT FK_authentication_holder_extension_owner_id FOREIGN KEY (owner_id) REFERENCES authentication_holder (id)
ALTER TABLE authentication_holder_request_parameter ADD CONSTRAINT authentication_holder_request_parameter_owner_id FOREIGN KEY (owner_id) REFERENCES authentication_holder (id)
ALTER TABLE client_authority ADD CONSTRAINT FK_client_authority_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_claims_redirect_uri ADD CONSTRAINT FK_client_claims_redirect_uri_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_contact ADD CONSTRAINT FK_client_contact_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_default_acr_value ADD CONSTRAINT FK_client_default_acr_value_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_grant_type ADD CONSTRAINT FK_client_grant_type_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_post_logout_redirect_uri ADD CONSTRAINT FK_client_post_logout_redirect_uri_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_redirect_uri ADD CONSTRAINT FK_client_redirect_uri_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_request_uri ADD CONSTRAINT FK_client_request_uri_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_resource ADD CONSTRAINT FK_client_resource_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_response_type ADD CONSTRAINT FK_client_response_type_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE client_scope ADD CONSTRAINT FK_client_scope_owner_id FOREIGN KEY (owner_id) REFERENCES client_details (id)
ALTER TABLE token_scope ADD CONSTRAINT FK_token_scope_owner_id FOREIGN KEY (owner_id) REFERENCES access_token (id)
ALTER TABLE access_token_permissions ADD CONSTRAINT FK_access_token_permissions_access_token_id FOREIGN KEY (access_token_id) REFERENCES access_token (id)
ALTER TABLE access_token_permissions ADD CONSTRAINT FK_access_token_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permission (id)
ALTER TABLE saved_user_auth_authority ADD CONSTRAINT FK_saved_user_auth_authority_owner_id FOREIGN KEY (owner_id) REFERENCES saved_user_auth (id)
ALTER TABLE approved_site_scope ADD CONSTRAINT FK_approved_site_scope_owner_id FOREIGN KEY (owner_id) REFERENCES approved_site (id)
ALTER TABLE whitelisted_site_scope ADD CONSTRAINT FK_whitelisted_site_scope_owner_id FOREIGN KEY (owner_id) REFERENCES whitelisted_site (id)
ALTER TABLE claim_token_format ADD CONSTRAINT FK_claim_token_format_owner_id FOREIGN KEY (owner_id) REFERENCES claim (id)
ALTER TABLE claim_issuer ADD CONSTRAINT FK_claim_issuer_owner_id FOREIGN KEY (owner_id) REFERENCES claim (id)
ALTER TABLE permission_scope ADD CONSTRAINT FK_permission_scope_owner_id FOREIGN KEY (owner_id) REFERENCES permission (id)
ALTER TABLE claim_to_permission_ticket ADD CONSTRAINT FK_claim_to_permission_ticket_claim_id FOREIGN KEY (claim_id) REFERENCES claim (id)
ALTER TABLE claim_to_permission_ticket ADD CONSTRAINT FK_claim_to_permission_ticket_permission_ticket_id FOREIGN KEY (permission_ticket_id) REFERENCES permission_ticket (id)
ALTER TABLE policy_scope ADD CONSTRAINT FK_policy_scope_owner_id FOREIGN KEY (owner_id) REFERENCES policy (id)
ALTER TABLE claim_to_policy ADD CONSTRAINT FK_claim_to_policy_claim_id FOREIGN KEY (claim_id) REFERENCES claim (id)
ALTER TABLE claim_to_policy ADD CONSTRAINT FK_claim_to_policy_policy_id FOREIGN KEY (policy_id) REFERENCES policy (id)
ALTER TABLE resource_set_scope ADD CONSTRAINT FK_resource_set_scope_owner_id FOREIGN KEY (owner_id) REFERENCES resource_set (id)
ALTER TABLE iam_account_authority ADD CONSTRAINT FK_iam_account_authority_authority_id FOREIGN KEY (authority_id) REFERENCES iam_authority (ID)
ALTER TABLE iam_account_authority ADD CONSTRAINT FK_iam_account_authority_account_id FOREIGN KEY (account_id) REFERENCES iam_account (ID)
ALTER TABLE iam_account_group ADD CONSTRAINT FK_iam_account_group_account_id FOREIGN KEY (account_id) REFERENCES iam_account (ID)
ALTER TABLE iam_account_group ADD CONSTRAINT FK_iam_account_group_group_id FOREIGN KEY (group_id) REFERENCES iam_group (ID)
