package it.infn.mw.iam.api.scim.new_updater;

public enum UpdaterType {

  ACCOUNT_REPLACE_GIVEN_NAME,
  ACCOUNT_REPLACE_FAMILY_NAME,
  ACCOUNT_REPLACE_EMAIL,
  ACCOUNT_REPLACE_PASSWORD,
  ACCOUNT_REPLACE_PICTURE,
  ACCOUNT_REPLACE_USERNAME,
  ACCOUNT_REPLACE_ACTIVE,

  ACCOUNT_ADD_OIDC_ID,
  ACCOUNT_ADD_SAML_ID,
  ACCOUNT_ADD_SSH_KEY,
  ACCOUNT_ADD_X509_CERTIFICATE,

  ACCOUNT_REMOVE_SAML_ID,
  ACCOUNT_REMOVE_OIDC_ID,
  ACCOUNT_REMOVE_SSH_KEY,
  ACCOUNT_REMOVE_X509_CERTIFICATE;

}