FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY iam_login_service.key.pem /etc/ssl/private/iam_login_service.key.pem
COPY iam_login_service.cert.pem /etc/ssl/certs/iam_login_service.cert.pem
