CREATE TABLE iam_email_notification (ID BIGINT IDENTITY NOT NULL, UUID VARCHAR(36) NOT NULL UNIQUE, NOTIFICATION_TYPE VARCHAR(128) NOT NULL, SUBJECT VARCHAR(128), BODY CLOB, CREATION_TIME TIMESTAMP NOT NULL, DELIVERY_STATUS VARCHAR(128), LAST_UPDATE TIMESTAMP, REQUEST_ID BIGINT, PRIMARY KEY (ID));
ALTER TABLE iam_email_notification ADD CONSTRAINT FK_iam_email_notification_request_id FOREIGN KEY (request_id) REFERENCES iam_reg_request (id);
CREATE TABLE iam_notification_receiver(ID BIGINT IDENTITY NOT NULL, NOTIFICATION_ID BIGINT, EMAIL_ADDRESS VARCHAR(254), PRIMARY KEY (ID));
ALTER TABLE iam_notification_receiver ADD CONSTRAINT FK_iam_notification_receiver_notification_id FOREIGN KEY (notification_id) REFERENCES iam_email_notification (id);
ALTER TABLE iam_reg_request ADD COLUMN notes CLOB;
